### ISSUE TITLE
Can't change parameters and more

### ISSUE THREAD

**Issue by remi-dandois** [cerberustesting/cerberus-source#2026]
Using version 4.2 of a brand new cerberus installation, things are going wrong.

I first logged in and clicked the "initialize databaze", evrerithing is OK.
Then, what I can do : 
    - Create/edit a test case and edit an existing test case
    - Create new environments in the "Integration" > "environment" page
    - Save new urls in the "application" > "application" page
    - Create/edit users
What I can't do (I change/create the value and, after clicking the "save" button, the loading animation keep spinning endlessly and, if I reaload the page, nothing is saved ):
    - Edit/create a new invariant
    - Edit queue job status parameters in the "Run" > "executions in queue" page

**Comment by Nouxx** [comment]
Hi,

We have experienced a few bugs (already corrected and added to the regression campaign), sorry!

I confirm that the parameter edition isn't possible ("queue job status" is one of them)

However, I am able to create & edit Invariants

**Comment by vertigo17** [comment]
Parameter update was fixed with https://github.com/cerberustesting/cerberus-source/commit/8bd860b098810c419b8bc886020272074e34bd6b
About invariant, I would be interested to get more detail.

**Comment by remi-dandois** [comment]
Thanks for your replies.
We will perform the uptade to Cerberus 4.3. 
Hopefully, this will solve the invariant bug as well.
The update and testing of Cerberus 4.3 will probably be performed this friday, I will give you feedbacks after that.

**Comment by vertigo17** [comment]
Thanks Remi, so it means you did not manage to reproduce issue on invariant.
If you manage to reporduce it, please provide details so that we can also on our side from qa environment.

**Comment by remi-dandois** [comment]
Update here,
After updating Cerberus to version 4.2, I tried again today.
I still have the same issue, and found out few more infos (screenshot attached)
![error-update-parameter](https://user-images.githubusercontent.com/54069464/72350531-e886a800-36de-11ea-9523-31ad67319518.png)

**Comment by vertigo17** [comment]
Issue was fixed in 4.3 not 4.2.
